#!/bin/bash
#
# Build releases for Linux/AMD64
#
# Since we output assembly language there's little point building for
# other systems.
#


export GOOS=linux
export GOARCH=amd64

go build -o "math-compiler-linux-amd64"
